### ISSUE TITLE
simbolito de bluesky

### ISSUE THREAD

**Issue by ClaraRuizG** [pablo-icm/emm#13]
pofavó

**Comment by pablo-icm** [comment]
Done. I have used a custom icon instead of fontAwesome set, as I couldn't make it to read the new version (where Bluesky is a thing). Followed this [post](https://discourse.gohugo.io/t/custom-icon-in-params-social-with-coder-theme/37163) but I ended up using the URL for the icon.

Solved in commit e9094cc
